### ISSUE TITLE
Contributed system version bump

### ISSUE THREAD

**Issue by lockie** [ocicl/ocicl#12]
Hello and thanks for interesting project in the area that sorely lacks nice working solutions (namely, CL dependencies isolation).

I have a theoretical question: suppose I post a system to include in ocicl repo. I can see that [issue template](https://github.com/ocicl/request-system-additions-here/issues/new?assignees=&labels=&projects=&template=request.yml&title=%5BSystem+Request%5D%3A+) contains a required field "Git commit hash". I was wondering how I'd be able to bump the version of that system in ocicl repo in case there were updates to it?

**Comment by atgreen** [comment]
Just send a PR or file a issue.  I have a script that notifies me of
updates, and have been handling them in an ad-hoc manner.  I will clean it
up and commit it to an ocicl-admin repo or similar.

Ultimately, I don't want to be the only one maintaining these repos.  I'm
hoping that once (if?) this gets traction, then people will be willing to
volunteer to help maintain it.

Thanks for your interest and feedback!

**Comment by lockie** [comment]
Got it, thank you!
