### ISSUE TITLE
Quicklisp interoperation

### ISSUE THREAD

**Issue by lockie** [ocicl/ocicl#14]
Hello!
Having both Quicklisp and ocicl installed, I've noticed that even when I'm calling `(ql:quickload :some-system)`, there is the `systems` folder and `systems.csv` file after I leave Lisp, which means ocicl also fiddles with how Quicklisp loads its libraries. Changing the order of initialization in `.sbclrc` does not help. I was wondering if it'd be possible for ocicl to keep Quicklisp loading the packages from its own locations (I reckon CLPM works like that).

**Comment by atgreen** [comment]
Both quicklisp and ocicl reply on ASDF for finding the systems.  When ASDF is searching for a system, it goes through a list of search functions called  `asdf:*system-definition-search-functions*`.   Both quicklisp and ocicl add their magic to this list.   The ocicl runtime simply appends to the list here: https://github.com/ocicl/ocicl/blob/17d555e465598c898f0ed93bb57c205519c583ab/runtime/ocicl-runtime.lisp#L114-L116 .  I believe quicklisp does something similar.  I haven't thought about how the two should interact, as I've stopped using quicklisp.  What do you recommend as the most reasonable behaviour?
