### ISSUE TITLE
Wrong paths in "setup" output

### ISSUE THREAD

**Issue by svetlyak40wt** [ocicl/ocicl#16]
I've installed ocicl with DESTDIR like this:

```
DESTDIR=~/.ocicl-root make install
```

And have got paths leading to `~/.local/share` instead of `~/.ocicl-root/share`:

```
mkdir -p /Users/art/.ocicl-root/bin || true ;
echo

echo Darwin
Darwin
echo "Installing for macOS arm64..."
Installing for macOS arm64...
cp ocicl /Users/art/.ocicl-root/bin ;
tar xvf oras/oras_1.0.1_darwin_arm64.tar.gz -C /tmp oras > /dev/null 2>&1;
mv /tmp/oras /Users/art/.ocicl-root/bin/ocicl-oras
/Users/art/.ocicl-root/bin/ocicl setup
;; Add the following to your lisp startup file (.sbclrc/.eclrc/.abclrc):

#-ocicl
(when (probe-file #P"/Users/art/.local/share/ocicl/ocicl-runtime.lisp")
  (load #P"/Users/art/.local/share/ocicl/ocicl-runtime.lisp"))
;; Any systems you install in /Users/art/.local/share/ocicl/
;; will be available globally unless you comment out this line:
(asdf:initialize-source-registry '(:source-registry :ignore-inherited-configuration (:tree #P"/Users/art/.local/share/ocicl/")))
```

It would be nice to provide a code ready to be inserted into config.

**Comment by atgreen** [comment]
Thanks for pointing this out. I'll have a look.

**Comment by atgreen** [comment]
Ok, having given this some thought....
DESTDIR is supposed to point at the install location for binaries, which could potentially be shared by users.  So DESTDIR=/usr or DESTDIR=/usr/local would make sense.  
The settings in your .sbclrc are supposed to be user specific.   On linux, I'm following the XDG spec (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ). So I think the current setup is correct. 
Maybe ocicl should read an OCICL_HOME environment variable to set the base directory for the user runtime files.  Does that make sense to you?

**Comment by svetlyak40wt** [comment]
This makes sense. In this case this new var should be mentioned in README.
