### ISSUE TITLE
Link to the "rekor transparency log" is broken

### ISSUE THREAD

**Issue by svetlyak40wt** [ocicl/ocicl#17]
README have this link: https://docs.sigstore.dev/rekor/overview/ but this page is "Not found".

**Comment by atgreen** [comment]
Perhaps it was a temporary error.  It seems to work for me.  Can you please
try again?

**Comment by atgreen** [comment]
I just tried it again, and it is fine.  I'm closing this, but please reopen if you experience this again.

**Comment by svetlyak40wt** [comment]
I still see the problem. I click URL https://docs.sigstore.dev/rekor/overview/

Site opens, but says "Page not found":

![Screenshot 2023-08-13 at 19 32 52](https://github.com/ocicl/ocicl/assets/24827/40b42dc7-b3da-44c0-8a93-e2ef71911d5c)

**Comment by svetlyak40wt** [comment]
Probably this link should be changed to https://docs.sigstore.dev/logging/overview/?

**Comment by atgreen** [comment]
Very weird.  That link still works for me... *except* when I try it in an
incognito window.  So, you are right -- the link is wrong.  I'll fix this!
