### ISSUE TITLE
What do you think about making Ultralisp.org ocicl compatible?

### ISSUE THREAD

**Issue by svetlyak40wt** [ocicl/ocicl#18]
Ultralisp already supports both Quicklisp and CLPM formats, probably it will be easy to add OCICL too.

But "Self Hosting" section of the readme does not describe how to create your own ocicl compatible distribution from scratch.
For example, if I have "Docker" compatible registry in some cloud, what do I need to do to publish a package and make ocicl client be able to download it?

**Comment by atgreen** [comment]
I don't know enough about ultralisp to understand what it means to make it ocicl compatible.  Can you explain what this would mean?
For ocicl, there's no concept of supporting multiple repos (apart from full mirrors).

**Comment by svetlyak40wt** [comment]
Here is how Ultralisp works:

1. It stores information about different lisp projects in the database. Whereas Quicklisp and OCICL use GitHub repositories to store metadata.
2. It is able to check if there are any new commits either by a webhook or by flexible scheduler. Whereas Quicklisp uses manual process and OCICL seems uses some sort of cron.
3. When new commits are arrived, Ultralisp builds a new tar.gz archive, uploads it to S3 and generates new metadata files for Quicklisp and CLPM distributions. These files are in different formats, but point to the same tar.gz archives.

I'm talking about an additional step 4, where Ultralisp will sign/upload tar.gz archive to the Docker Hub (or other registry) and probably will update some metadata files to make this update visible to OCICL client.

In this way, we will exclude process of adding new projects via GitHub issues and storing metadata information in thousands repositories. It will be more convenient to maintain for us and more convenient to consume for OCICL users.

**Comment by svetlyak40wt** [comment]
When I talked about a few registries, I meant this idea:

Why don't we want to let user to point ocicl to a few registries and if some ASDF system wasn't found in first registry, then lookup it in the next?

This way somebody might publish it's own packages in his own registry but download third-party packages from the main ocicl registry without having to copy all packages to his registry and syncronize from time to time.

**Comment by svetlyak40wt** [comment]
I've read through code in https://github.com/ocicl/ocicl-action/blob/main/action.yml and seems it will be easy to upload artefacts to some registry from Ultralisp! Horay!

Now I need to take another vacation to work on this feature :(

**Comment by svetlyak40wt** [comment]
The only thing I can't figure out is how do you make a list of systems of the project.

For example, this [metadata for CFFI project](https://github.com/ocicl/cffi) list only a few ASDF systems, but [cffi.asd](https://github.com/cffi/cffi/blob/master/cffi.asd) contains more. As I understand, these additional systems will not be visible to osicl client unless you install `cffi` system (or other system listed in metadata).

Shouldn't these additional systems also be listed in metadata? How about package-inferred subsystems, should they be listed too?

**Comment by atgreen** [comment]
In that example of cffi, ASDF does all of the magic to find `:cffi/c2ffi`. 
```
[green@fedora tmp]$ sbcl
This is SBCL 2.3.4, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (setf ocicl-runtime:*download* t)
T
* (setf ocicl-runtime:*verbose* t)
T
* (asdf:load-system :cffi/c2ffi)
; running: ocicl install cffi
ocicl install cffi
; downloaded ghcr.io/ocicl/cffi@sha256:6af27c3bcfd00c475feb467a62f51e0c83faa2c8d8858a0d49af40c59697f5be
; downloaded ghcr.io/ocicl/alexandria@sha256:721cedc4d790274a1e8a8e7239aef8e82d0ab5d530aad83ceb0da0d773bf7cb1
; downloaded ghcr.io/ocicl/trivial-features@sha256:9da86d54aeabcaeb43e69e0a1d6d04c42d9446f2094c8752d89d4ca6ba1b7cbd
; downloaded ghcr.io/ocicl/babel@sha256:6d94ae594a1f6ad44781b1a41d899f7b07b61c5a362e265241d69516dbd70f7f

; loading /tmp/systems.csv
; checking for /tmp/systems/cffi-20230809-c42b42e/cffi.asd: found
; checking for /tmp/systems/alexandria-20230813-db1288f/alexandria.asd: found
; checking for /tmp/systems/trivial-features-1.0/trivial-features.asd: found
; checking for /tmp/systems/babel-20230809-627d6a6/babel.asd: found
; compiling file "/tmp/systems/cffi-20230809-c42b42e/src/c2ffi/package.lisp" (written 17 AUG 2023 06:32:36 AM):

; wrote /home/green/.cache/common-lisp/sbcl-2.3.4-linux-x64/tmp/systems/cffi-20230809-c42b42e/src/c2ffi/package-tmpAAURSO1.fasl
; compilation finished in 0:00:00.002
; compiling file "/tmp/systems/cffi-20230809-c42b42e/src/c2ffi/c2ffi.lisp" (written 17 AUG 2023 06:32:36 AM):

; file: /tmp/systems/cffi-20230809-c42b42e/src/c2ffi/c2ffi.lisp
; in: DEFVAR *C2FFI-EXTRA-ARGUMENTS*
;     (LIST)
; 
; note: deleting unreachable code


; wrote /home/green/.cache/common-lisp/sbcl-2.3.4-linux-x64/tmp/systems/cffi-20230809-c42b42e/src/c2ffi/c2ffi-tmp5GEXGEG5.fasl
; compilation finished in 0:00:00.014
; compiling file "/tmp/systems/cffi-20230809-c42b42e/src/c2ffi/asdf.lisp" (written 17 AUG 2023 06:32:36 AM):

; wrote /home/green/.cache/common-lisp/sbcl-2.3.4-linux-x64/tmp/systems/cffi-20230809-c42b42e/src/c2ffi/asdf-tmpAR3FSGEY.fasl
; compilation finished in 0:00:00.016
; 
; compilation unit finished
;   printed 1 note
T
* 
```

Although I haven't tested it, I don't believe the ocicl-runtime interferes with package-inferred subsystems.  You would still need to load the top-level system, possibly handled by ocicl-runtime, and then ASDF handles takes care of the package-inferred subsystems without relying on ocicl-runtime.

**Comment by svetlyak40wt** [comment]
Aha! I've made a number of experiments and found that my previous problems with loading subsystems of a package-inferred systems were caused Quicklisp's client code. When using ASDF + OCICL everything works just fine!

**Comment by svetlyak40wt** [comment]
So, to summarize. To make a OCICL compatible distribution, I need to create an OCI registry and to publish tar.gz. archives for all primary asdf system names.

**Comment by atgreen** [comment]
Yes, that's right.  And you can point ocicl at it with `ocicl setup -r ghcr.io/ultralisp` or similar.
