### ISSUE TITLE
make install fails on macOS x86_64

### ISSUE THREAD

**Issue by rudolfochrist** [ocicl/ocicl#19]
Hi @atgreen,

after creating several failed examples of a new package manager for CL myself(e.g. [rudolfochrist/cl-manager](https://github.com/rudolfochrist/cl-manager)), I'm fully converted to `ocicl` now. Thank you. 😊

I'm on an older Mac and installation didn't work as expected (or documented). `make install` fails:

```shell
[lispm@Genera.local (git)-[main]- ocicl]% uname -a
Darwin Genera.local 20.6.0 Darwin Kernel Version 20.6.0: Thu Jun  8 22:36:09 PDT 2023; root:xnu-7195.141.49.701.4~1/RELEASE_X86_64 x86_64
[lispm@Genera.local (git)-[main]- ocicl]% DESTDIR=./tmp make install
mkdir -p ./tmp/bin || true ;
echo

echo Darwin
Darwin
echo "Installing for macOS x86_64..."
Installing for macOS x86_64...
cp ocicl ./tmp/bin ;
tar xvf oras/oras_1.0.1_darwin_x86_64.tar.gz -C /tmp oras > /dev/null 2>&1;
make: *** [Makefile:22: install] Error 1
``` 

Untar of `oras/oras_1.0.1_darwin_x86_64.tar.gz` fails because this tarball doesn't exist. The oras-project also doesn't have any releases for Darwin x86_64 attached ([oras-1.0.1](https://github.com/oras-project/oras/releases/tag/v1.0.1)).

I got it working by installing `oras` over homebrew, but thought it would be good to report it. 

Greetings,
Sebastian

**Comment by atgreen** [comment]
I think I've fixed this just now by mapping x64_64  to amd64.  Could you please try again?
