### ISSUE TITLE
Inherit ASDF configuration

### ISSUE THREAD

**Issue by yitzchak** [ocicl/ocicl#27]
It might be better to change the following to following to `:inherit-configuration` as the current suggestion wipes out the default ASDF [configuration](https://asdf.common-lisp.dev/asdf.html#Configuring-ASDF-to-find-your-systems-1) and any current configuration the user has set up.

https://github.com/ocicl/ocicl/blob/6b10958f2efc0957839d0e862939ec0c40ec2ba0/ocicl.lisp#L221

**Comment by atgreen** [comment]
Thanks.  I've fixed this in 2.0.1.
