### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by MarcRohrer** [ocicl/ocicl#29]
Hi,

in the office, everything worked fine under windows 10.
At home, I run Windows 11, I get a compile error:

```
H:\src\lisp\ocicl-main>make
rm -rf systems systems.csv;
sbcl --dynamic-space-size 3072 --no-userinit --eval "(require 'asdf)" --eval "(progn (push (uiop:getcwd) asdf:*central-registry*) (asdf:make :ocicl) (sb-ext:quit))"
This is SBCL 2.3.2, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
fatal error encountered in SBCL pid 3540835412:
GC invariant lost, file "win32-os.c", line 836


H:\src\lisp\ocicl-main>
```

What is the problem? I do not really understand :-(

Marc

**Comment by atgreen** [comment]
This looks like an SBCL bug. Try installing a newer version.

AG

**Comment by MarcRohrer** [comment]
Hi Anthony,

2.3.2 is the current version under Windows as I understand.
I have the same version at the office.

I did a complete reinstall anyway.

No change. Still

GC invariant lost, file "win32-os.c", line 836

I am very disappointed :-(

Marc

**Comment by rudolfochrist** [comment]
> 2.3.2 is the current version under Windows as I understand.

No. The most recent version of SBCL is 2.4.1. (as of today Feb 24, 2024). The SBCL home pages doesn't provide a downloadable windows executable for this version. If you want a more recent version of SBCL on Windows, you have to compile it yourself. 

> I have the same version at the office.

But there you run Windows 10. Seems that SBCL 2.3.2 has issues with Windows 11. Hence try upgrading SBCL to the newest version.

**Comment by atgreen** [comment]
Interesting.  I had to increase dynamic-space-size in order for ocicl to
download/build random-sampler.   How much memory does your Windows machine
have?

AG

**Comment by MarcRohrer** [comment]
Hi Anthony,

home: 64GB
office: 32GB

I do not hav a clear recollection, but we had problems with this
parameter, when I first started with OCICL. But I think, that was a 
different error, so I did not relate the error to that...

Thanx!

Marc

**Comment by atgreen** [comment]
I believe that this was addressed by setting +dynamic-space-size+ at setup time.
