### ISSUE TITLE
systems in module

### ISSUE THREAD

**Issue by MarcRohrer** [ocicl/ocicl#30]
Hi,

is it normal, that ocicl also creates a systems.csv and directory in a module/subdirectory?

![grafik](https://github.com/ocicl/ocicl/assets/110817144/e947f197-f44c-41c0-9d50-59bb3a086427)

contents is:

```
asdf-package-system, ghcr.io/ocicl/asdf-package-system@sha256:bafeb9d6e67cb280100080a2382f24558964ecf37029ff904b932c6c7d0e9c33, asdf-package-system-20230809-61776f2/asdf-package-system.asd
```

Marc

**Comment by atgreen** [comment]
I could never reproduce this.
