### ISSUE TITLE
Roswell support

### ISSUE THREAD

**Issue by kilianmh** [ocicl/ocicl#33]
I'm trying to set up `ocicl` on my machine using `roswell`.

Is there a way to do that? 

If yes, then some documentation would be nice. 
Otherwise adding support could make `ocicl` accessible to a larger user base.

**Comment by atgreen** [comment]
I'm not very familiar with `roswell`, but it seems that it is pretty hard-coded to `quicklisp`.   

Have you tried installing `ocicl` as documented, and then putting something like the following in your `~/.roswell/init.lisp` file?:
```
#-ocicl
(when (probe-file #P"/home/green/.local/share/ocicl/ocicl-runtime.lisp")
  (load #P"/home/green/.local/share/ocicl/ocicl-runtime.lisp"))
(push (uiop:getcwd) asdf:*central-registry*)
(setf ocicl-runtime:*verbose* nil)
(setf ocicl-runtime:*download* t)
```
Let me know if that works.

**Comment by atgreen** [comment]
It seems to work fine.  I've update the readme, and `ocicl setup` now says:
```
;; Add the following to your lisp startup file
;; (~/.sbclrc, ~/.eclrc, ~/.abclrc or ~/.roswell/init.lisp):

#-ocicl
(when (probe-file #P"/home/green/.local/share/ocicl/ocicl-runtime.lisp")
  (load #P"/home/green/.local/share/ocicl/ocicl-runtime.lisp"))
(push (uiop:getcwd) asdf:*central-registry*)
```
