### ISSUE TITLE
Windows installation not working out of the box.

### ISSUE THREAD

**Issue by simendsjo** [ocicl/ocicl#34]
Just found this, and it pretty much worked straight out of the box! Amazing!

Makefiles doesn't work very well on Windows though. I manually ran the steps from the makefile and notice it references oras/oras_1.1.0_windows_amd64.gz, which doesn't exists. There is a zip, but running that through install.lisp failed. But I noticed the install script just unpacked which worked fine.

So the Windows installation could be more seamless.

**Comment by atgreen** [comment]
Thanks!  We should really just have a lisp-based installer.  Let me know if you want to write it!

**Comment by atgreen** [comment]
I wrote a lisp-based installer, although I'm not sure it works on Windows yet.  I also fixed the oras binary problem.  Please have a look, and patches for any problems would be very welcome!

**Comment by atgreen** [comment]
I've been testing it on Windows, and it seems fine now.
