### ISSUE TITLE
ocicl --global semantics

### ISSUE THREAD

**Issue by simendsjo** [ocicl/ocicl#35]
I wanted to store all systems in a global location, and was expecting `--global` to do this. I found a bug when reading the ocicl-globaldir.cfg where the content it read always includes a newline (at least on windows), causing uiou:chdir to fail. (my fix is basically `(setf *ocicl-globaldir* (uiop:ensure-absolute-pathname (uiop:read-file-line config-file)))`

But nothing happened when I ran `ocicl -g install`. Looks like this will change directory to the global directory and use the systems.csv at that location.

I was expecting it to use the systems.csv in my project location, but store globally (and maybe symlink to my project).
Or maybe merge the content of my projects system.csv to the global system.csv first.
Either way, I expected it to install systems defined in my project, but install them globally.

EDIT: Or maybe (read-systems-csv) should be read before changing directory?
```patch
diff --git a/ocicl.lisp b/ocicl.lisp
index 42486b5..496d817 100644
--- a/ocicl.lisp
+++ b/ocicl.lisp
@@ -286,9 +286,9 @@ Distributed under the terms of the MIT License"
       (let ((original-directory (uiop:getcwd)))
         (unwind-protect
             (progn
+              (setq *ocicl-systems* (read-systems-csv))
               (uiop:chdir workdir)
               (setf *random-state* (make-random-state t))
-              (setq *ocicl-systems* (read-systems-csv))
               (setq *systems-dir* (merge-pathnames (make-pathname :directory '(:relative "systems"))
                                                    (uiop:getcwd)))
               (if (not (> (length free-args) 0))
```

**Comment by atgreen** [comment]
Thanks for your comments.  I'll revisit this in a couple of days.

**Comment by atgreen** [comment]
Having given this some thought, I won't be changing the current behavior.  The global and local systems are separate.  The semantics are clean when you consider that all "-g" does is switch you to the global directory before performing any operation.  If you have a systems.csv file that you want to install globally, just add the contents to your global systems.csv files, and run `ocicl -g install`.

**Comment by simendsjo** [comment]
> Having given this some thought, I won't be changing the current behavior. The global and local systems are separate.

Is there a way to use a global cache? I don't want all projects to have their own bitwise identical copy of all dependencies.

**Comment by atgreen** [comment]
Yes, look at the last line from `ocicl setup` output:

```
$ ocicl setup
;; Add the following to your lisp startup file (.sbclrc/.eclrc/.abclrc):

#-ocicl
(when (probe-file #P"/home/green/.local/share/ocicl/ocicl-runtime.lisp")
  (load #P"/home/green/.local/share/ocicl/ocicl-runtime.lisp"))
;; Any systems you install in /home/green/.local/share/ocicl/
;; will be available globally unless you comment out this line:
(asdf:initialize-source-registry '(:source-registry :inherit-configuration (:tree #P"/home/green/.local/share/ocicl/")))
```

And then just install systems with `-g`, like so:  `ocicl -g install cl-ppcre cl-etcd`.

**Comment by simendsjo** [comment]
Running `sbcl --eval '(asdf:load-system foo)'` in the foo folder, I get systems.csv and systems/ containing all libraries.
Even if I did `ocicl install -g alexandria` in foo, the system.csv in foo wouldn't get updated with the version.

So I'll have to do "load-system 'foo" in foos directory, then move everything from systems to the global cache.
Then do "load-system 'bar" in bars directory, move everything from systems to the global cache.
And so on.

But maybe I'm missing something? I'd like to have the lockfile (which system.csv is..?) in the project folder, but all artifacts in the global cache to avoid downloading the same systems for each project.

**Comment by atgreen** [comment]
Yes, I agree.  Here's how I'm thinking of changing things.  Let me know if this works for you.

When ocicl-runtime searches for a system, it will look for a local copy first (systems.csv in current directory).  If it's not there, then it will look for a global copy.  If it's not there, and `ocicl-runtime:*download*` is true, then it will try to download it locally.  It will never try to download globally. You have to used the `ocicl` cli to manage the global systems.  One of the reasons is that I don't want to have to worry about file locking and dealing with multiple programs wanting to manage the global systems.csv at the same time.

What do you think?

Currently the global store depends on you having configured asdf to look in the global directory, but that is fragile, and ocicl may  currently download locally depending on the order it searches for things.
