### ISSUE TITLE
raspi

### ISSUE THREAD

**Issue by MarcRohrer** [ocicl/ocicl#37]
Hi,

sorry! I feel like covering all the edge cases :-(

I currently am at the European Lisp Symposium in Vienna, ans as I do not have a laptop, I decided to bring a raspberry pi 400, for which I bought a small monitor for that occasion.

All the installations worked, but OCICL oly gives me errors, that the requested library is not found.

Digging some more into this, ocicl-oras called directly gives

```
marc.rohrer@ansset-400:~ $ ocicl-oras pull ghcr.io/ocicl/str:latest
bash: /home/marc.rohrer/.local/bin/ocicl-oras: Kann die Binärdatei nicht ausführen: Fehler im Format der Programmdatei
```

so I guess, this is the wrong executable for ARM?

Marc

**Comment by atgreen** [comment]
Yes.. I don't do this right for ARM Linux yet.   You can download the ARM
Linux oras binary from here ...
https://github.com/oras-project/oras/releases/tag/v1.1.0
..and rename is to ocicl-oras.

I'll try to fix this properly soon.

Enjoy ELS -- I hope to go some day.

AG

**Comment by MarcRohrer** [comment]
Ok, thanx!Am 02.05.2024 12:43 schrieb Anthony Green ***@***.***>:
Yes.. I don't do this right for ARM Linux yet.   You can download the ARM

Linux oras binary from here ...

https://github.com/oras-project/oras/releases/tag/v1.1.0

..and rename is to ocicl-oras.



I'll try to fix this properly soon.



Enjoy ELS -- I hope to go some day.



AG

**Comment by atgreen** [comment]
I think this is fixed now.

**Comment by MarcRohrer** [comment]
unfortuately note quite 

```
mkdir -p /home/marc.rohrer/.local/bin || true ;
Installing for Linux...
cp ocicl /home/marc.rohrer/.local/bin ;
Unsupport macOS type: aarch64
mv: der Aufruf von stat für '/tmp/oras' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
make: *** [Makefile:20: install] Fehler 1

```
