### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by Immortalin** [ocicl/ocicl#42]
It would make installation easier if there is a homebrew package. SBCL (https://formulae.brew.sh/formula/sbcl) can be used as the default lisp and oras (https://formulae.brew.sh/formula/oras) can be added as a dependency.

**Comment by boogsbunny** [comment]
[Duplicate](https://github.com/ocicl/ocicl/issues/39)

**Comment by atgreen** [comment]
My homebrew formula was just merged. I'm not sure how long it takes to show up, but from my perspective, this is done.

https://github.com/Homebrew/homebrew-core/pull/172754
