### ISSUE TITLE
homebrew build fails when you `setup` into a non-existant directory

### ISSUE THREAD

**Issue by dieggsy** [ocicl/ocicl#44]
I have installed ocicl from homebrew. I get the following error when I try to change the `GLOBALDIR`, not sure what's going on:

```
┌─[~]
!─╼ ocicl setup /Users/dieggsy/.local/lib/ocicl/
CORRUPTION WARNING in SBCL pid 17877 pthread 0x1fb954c00:
Memory fault at 0x102708000 (pc=0x7003b1acf4)
The integrity of this image is possibly compromised.
Exiting.
   0:     0x103441b00 pc=0x7003b1acf0 {0x7003b1ab10+01e0} SB-IMPL::OUTPUT-BYTES/UTF-8/LF
   1:     0x103441aa0 pc=0x7003973e30 {0x7003973ae0+0350} SB-IMPL::FD-SOUT
   2:     0x103441a50 pc=0x7003077500 {0x70030772d0+0230} SB-IMPL::%WRITE-STRING
   3:     0x1034418a0 pc=0x7004dffa30 {0x7004dff840+01f0} "fmt$GP044MDGA42V"
   4:     0x103441850 pc=0x700304dd40 {0x700304da90+02b0} FORMAT
   5:     0x1034417e0 pc=0x700304dc00 {0x700304da90+0170} FORMAT
   6:     0x103441630 pc=0x7004e00050 {0x7004dff840+0810} OCICL::DO-SETUP
   7:     0x103441408 pc=0x7004e0b3d0 {0x7004e0a510+0ec0} OCICL::MAIN
   8:     0x103441338 pc=0x70037ebb10 {0x70037eb350+07c0} SB-INT::SIMPLE-EVAL-IN-LEXENV
   9:     0x103441310 pc=0x700318b120 {0x700318afe0+0140} SB-EXT::EVAL-TLF
  10:     0x103441078 pc=0x7003096390 {0x7003094d80+1610} (LABELS SB-FASL::EVAL-FORM :IN SB-INT::LOAD-AS-SOURCE)
  11:     0x103440f20 pc=0x7003095c80 {0x7003094d80+0f00} (LAMBDA (SB-KERNEL::FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT::LOAD-AS-SOURCE)
  12:     0x103440e50 pc=0x7003108f60 {0x7003108b10+0450} SB-C::%DO-FORMS-FROM-INFO
  13:     0x103440c00 pc=0x7003095630 {0x7003094d80+08b0} SB-INT::LOAD-AS-SOURCE
  14:     0x103440ab8 pc=0x7003106dc0 {0x7003106130+0c90} (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD)
  15:     0x103440a00 pc=0x7003097d40 {0x70030979c0+0380} SB-FASL::CALL-WITH-LOAD-BINDINGS
  16:     0x1034408b0 pc=0x7003106b00 {0x7003106130+09d0} LOAD
  17:     0x103440798 pc=0x70030937f0 {0x7003092b10+0ce0} (FLET SB-IMPL::LOAD-SCRIPT :IN SB-IMPL::PROCESS-SCRIPT)
  18:     0x1034406c0 pc=0x7003093140 {0x7003092b10+0630} (FLET SB-UNIX::BODY :IN SB-IMPL::PROCESS-SCRIPT)
  19:     0x1034405c8 pc=0x7003092f00 {0x7003092b10+03f0} (FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-IMPL::PROCESS-SCRIPT)
  20:     0x1034404f0 pc=0x7003092d70 {0x7003092b10+0260} SB-IMPL::PROCESS-SCRIPT
  21:     0x103440278 pc=0x7003054cf0 {0x7003054240+0ab0} SB-IMPL::TOPLEVEL-INIT
  22:     0x1034401b0 pc=0x7003054040 {0x7003053a80+05c0} (FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP)
  23:     0x1034400c8 pc=0x7003053e60 {0x7003053a80+03e0} (FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP)
  24:     0x103440000 pc=0x7003053cd0 {0x7003053a80+0250} SB-IMPL::%START-LISP
```

**Comment by dieggsy** [comment]
I think I figured this out. The directory didn't exist and the error was very unintuitive

**Comment by atgreen** [comment]
I'd like to get to the bottom of this.  What does `ocicl version` say?

Here's what I get:
```
green@fedora:~$ ocicl setup /does/not/exist
Error: directory /does/not/exist does not exist.
```

**Comment by dieggsy** [comment]
Here's `ocicl version`:

```
┌─[~]
!─╼ ocicl version
ocicl version:   2.3.7
Lisp runtime:    SBCL 2.4.5
ASDF version:    3.3.1
```

**Comment by atgreen** [comment]
Interesting.  There are only two calls to format in `do-setup`.  One is to print the error message when the directory doesn't exist:
```
            (error (e)
              (declare (ignore e))
              (format uiop:*stderr* "Error: directory ~A does not exist.~%" (car args))
              (sb-ext:quit)))
```

I wonder if there was some problem with `uiop:*stderr*`?  What host OS are you on?

**Comment by dieggsy** [comment]
This is macOS Sonoma 14.5 with an M3 Max processor. This is probably not actually very useful but `uiop:*stderr*` appears to be fine in a fresh sbcl 2.4.5 repl.

**Comment by atgreen** [comment]
Are you able to reproduce this at will?

**Comment by dieggsy** [comment]
Yes, whenever I call `ocicl setup` with a directory that does not exist, I get the same error above.

**Comment by atgreen** [comment]
Could you please try this same thing with the `issue-44` branch, and share the output with me?

**Comment by dieggsy** [comment]
Ok, so interestingly, if I build `ocicl` myself from `main` I do get the expected output:
```
┌─[~/src/ocicl]─(main~)
└─╼ ./ocicl setup /does/not/exist
Error: directory /does/not/exist does not exist.
```
Here's the output from the issue-44 branch anyway
```
┌─[~/src/ocicl]─(issue-44~)
└─╼ ./ocicl setup /does/not/exist

#<SB-POSIX:SYSCALL-ERROR {7005426A23}>
("/does/not/exist")
Error: directory /does/not/exist does not exist.
#<SB-SYS:FD-STREAM for "standard error" {7005460223}>
"That worked." %
```
I guess this means there may be something wrong with the homebrew build?

**Comment by atgreen** [comment]
Hmm... is there an update for the homebrew build?  Can you make sure that
you have the latest sbcl and ocicl from homebrew?

**Comment by atgreen** [comment]
I can reproduce this on Linux!

***@***.***:~$ ocicl setup /tmp/sdfgaewsdrga
CORRUPTION WARNING in SBCL pid 1907699 tid 1907699:
Memory fault at 0x7f6136a0d000 (pc=0x550170e2 [code 0x55016ef0+0x1F2 ID
0x4a1c], fp=0x7ff20b7fe8f0, sp=0x7ff20b7fe898) tid 1907699
The integrity of this image is possibly compromised.
Exiting.
   0: fp=0x7ff20b7fe8f0 pc=0x550170e2 SB-IMPL::OUTPUT-BYTES/UTF-8/LF
   1: fp=0x7ff20b7fe948 pc=0x5485c13e SB-IMPL::FD-SOUT
   2: fp=0x7ff20b7fe978 pc=0x54744813 SB-IMPL::%WRITE-STRING
   3: fp=0x7ff20b7fead8 pc=0x5461f971 "fmt$GP044MDGA42V"
   4: fp=0x7ff20b7feb20 pc=0x5460ca0b FORMAT
   5: fp=0x7ff20b7feb80 pc=0x5460c8e9 FORMAT
   6: fp=0x7ff20b7fece0 pc=0x5461ffb2 OCICL::DO-SETUP
   7: fp=0x7ff20b7feea8 pc=0x54c2064c OCICL::MAIN
   8: fp=0x7ff20b7fef78 pc=0x547eec9b SB-INT::SIMPLE-EVAL-IN-LEXENV
   9: fp=0x7ff20b7fefa0 pc=0x548b224b SB-EXT::EVAL-TLF
  10: fp=0x7ff20b7ff1f8 pc=0x548cf90f (LABELS SB-FASL::EVAL-FORM :IN
SB-INT::LOAD-AS-SOURCE)
  11: fp=0x7ff20b7ff310 pc=0x548cf28b (LAMBDA (SB-KERNEL::FORM &KEY
:CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT::LOAD-AS-SOURCE)
  12: fp=0x7ff20b7ff3c0 pc=0x54869927 SB-C::%DO-FORMS-FROM-INFO
  13: fp=0x7ff20b7ff5d0 pc=0x548cebe3 SB-INT::LOAD-AS-SOURCE
  14: fp=0x7ff20b7ff6e8 pc=0x5472c34d (LABELS SB-FASL::LOAD-STREAM-1 :IN
LOAD)
  15: fp=0x7ff20b7ff780 pc=0x548cfdbf SB-FASL::CALL-WITH-LOAD-BINDINGS
  16: fp=0x7ff20b7ff8b0 pc=0x5472c06f LOAD
  17: fp=0x7ff20b7ff990 pc=0x54a77857 (FLET SB-IMPL::LOAD-SCRIPT :IN
SB-IMPL::PROCESS-SCRIPT)
  18: fp=0x7ff20b7ffa30 pc=0x54a77197 (FLET SB-UNIX::BODY :IN
SB-IMPL::PROCESS-SCRIPT)
  19: fp=0x7ff20b7ffaf0 pc=0x54a76f2e (FLET "WITHOUT-INTERRUPTS-BODY-" :IN
SB-IMPL::PROCESS-SCRIPT)
  20: fp=0x7ff20b7ffb90 pc=0x54a76d67 SB-IMPL::PROCESS-SCRIPT
  21: fp=0x7ff20b7ffdd8 pc=0x54a786a4 SB-IMPL::TOPLEVEL-INIT
  22: fp=0x7ff20b7ffe70 pc=0x54bc8094 (FLET SB-UNIX::BODY :IN
SB-IMPL::START-LISP)
  23: fp=0x7ff20b7fff30 pc=0x54bc7e9b (FLET "WITHOUT-INTERRUPTS-BODY-3" :IN
SB-IMPL::START-LISP)
  24: fp=0x7ff20b7fffc8 pc=0x54bc7cc8 SB-IMPL::%START-LISP

**Comment by atgreen** [comment]
Minimal reproducer:
```
#!/bin/sh                                                                                                                     
sbcl --no-userinit --eval "(require 'asdf)" --eval "(defun main () (format uiop:*stderr* \"~&Fail~%\"))" --eval "(sb-ext:save\
-lisp-and-die \"bug.core\")"
sbcl --core bug.core --eval "(main)"
```
