### ISSUE TITLE
Project or env level systems

### ISSUE THREAD

**Issue by dieggsy** [ocicl/ocicl#45]
Local systems currently default to come from the current working directory. It'd be nice to have project level systems that will load from a particular location. I'm trying to achieve something similar to [quicklisp library bundles](https://www.quicklisp.org/beta/bundles.html).

Looking at `ocicle-runtime.lisp`, it seems like I could do something like include `ocicl-runtime.lisp` in the project with the values of `*local-systems-dir*` and `*local-systems-csv*` manually set to the directory where I want the project systems.

Does this seem right? If so, it might be nice to have a note about this use case in the README. It could also be nice to explicitly support that use case in the command line tool - some kind of `ocicl project-init /local/ocicl/dir` that does the above.

By the way, thanks for working on ocicl. I really like the versioned approach, clean infrastructure, and command line option.

**Comment by atgreen** [comment]
You should be able to just:
```
(push #p"/my/special/place" asdf:*central-registry*)
```
And then `cd /my/special/place` to `ocicl install` things.   Or do you mean something else?

**Comment by atgreen** [comment]
And .. thank you!

**Comment by dieggsy** [comment]
That still requires `ocicl-runtime` to be loaded for the asdf search function, right? The reason I compared to quicklisp library bundles is that doesn't actually require quicklisp to be installed to use, the bundle file can just be loaded and asdf systems will be loaded from the right place.

That's why I suggested including ocicl-runtime, but it's possible I'm going about this the wrong way

**Comment by atgreen** [comment]
In that case, try:
```
(asdf:initialize-source-registry 
  '(:source-registry 
    (:tree "/path/to/my/library/collection/")
    :inherit-configuration))
```
This does not require the ocicl runtime.

**Comment by dieggsy** [comment]
Awesome, that works well!
