### ISSUE TITLE
Compile on Windows

### ISSUE THREAD

**Issue by MarcRohrer** [ocicl/ocicl#5]
Hi,

on Reddit I was recommended to use ocicl instead of Quicklisp. I wanted to try it, but make immediately fails:

----
rm -rf systems systems.csv;
sbcl --dynamic-space-size 2560 --no-userinit --eval "(require 'asdf)" --eval "(progn (push (uiop:getcwd) asdf:*central-registry*) (asdf:make :ocicl) (sb-ext:quit))"
This is SBCL 2.3.2, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
fatal error encountered in SBCL pid 149203212:
GC invariant lost, file "win32-os.c", line 836

make: *** [Makefile:3: ocicl] Error 1
----

What is the problem?

best wishes!

Marc

**Comment by atgreen** [comment]
"GC invariant lost" is an internal sbcl problem.   That is odd, because I
do CI testing of Windows builds.   See
https://github.com/ocicl/ocicl/actions/runs/5322994808/jobs/9640185145#step:7:37

What version of Windows are you using?

**Comment by MarcRohrer** [comment]
I use Windows 10 Version 22H2.
Thanx!

**Comment by MarcRohrer** [comment]
Hi Anthony,

installation with removed option was successful. Thank you!

best wishes!

Marc
