### ISSUE TITLE
ocicl installed ancient versions

### ISSUE THREAD

**Issue by rabbibotton** [ocicl/ocicl#50]
Today went to work on documenting OCICL with CLOG

In stalled ancient versions of CLOG and many other systems. How do I install and update the latest "world". This is not a great default situation....

**Comment by rabbibotton** [comment]
ocicl latest clog

did nothing to upgrade to the latest clog from my project - still one from clog-20240503-76468c7

**Comment by rabbibotton** [comment]
I did a ocicl list clog - and nothing is ancient versions only. Why? Also I need to make sure that all dependencies are updated to latest versions not just clog. CLOG plugins need to match CLOG for example etc

**Comment by atgreen** [comment]
It's likely because that was the last time it built successfully without
quicklisp.   You can go to look at the GitHub actions logs for
HTTPS://GitHub.com/ocicl/clog

**Comment by rabbibotton** [comment]
I am not sure what I am looking at or where any logs are? Also where would I find (once I understand this) clog-ace and clog-terminal its dependency systems?

**Comment by rabbibotton** [comment]
Is there an easy way to build with ocicl that does not require me to swap out my .sbclrc file every time to remove quicklisp?

**Comment by rabbibotton** [comment]
Is there a way to tell ocicl to give me latest with out concern if the head versions are compiling on some third party server? way to force a specific git version?

**Comment by rabbibotton** [comment]
I have update the CLOG Builder for working with OCICL and it is awesome.. but not picking up my github changes. Is there something I have to do? A timeframe involved?

**Comment by atgreen** [comment]
The ocicl build machinery scans repos for updates every 4hrs.

**Comment by atgreen** [comment]
Each project has it's own git repo, like  https://github.com/ocicl/clog.  These repos just contain metadata.   The most recent git commit hash is updated in the metadata whenever we detect an update in the corresponding project (checked every 4hrs).  The update to the metadata triggers a github actions build.  You can see the history of builds for clog here: https://github.com/ocicl/clog .   You can review the logs for those builds there as well.   Whenever we have a successful build, the clog tarball is updated in the ocicl OCI repository.   So you can periodically check for failures in the logs.  Or I can look into adding you to the list of recipients for failed build notifications for clog.

**Comment by rabbibotton** [comment]
I have made updates to CLOG to play super nice with OCICL

You can now create a directory and then cd in

ocicl setup >init
ocicl install clog
sbcl --userinit init
* (asdf:load-system :clog/tools)
* (clog-tools:clog-builder)

Setups your project and full IDE and GUI Builder ready to go.

Thanks for the amazing system.

**Comment by atgreen** [comment]
Cool.  I just tried this...any ideas?
```
* (clog-tools:clog-builder)
Starting non-quicklisp dir based system - CLOG
New System - Creating Project /home/green/CLOG/CLOG.asd
Template copy /home/green/CLOG/systems/clog-20240709-04d2a42/templates/projects/clog/ with www /home/green/CLOG/systems/clog-20240709-04d2a42/templates/www/ to /home/green/CLOG/
WARNING: System definition file #P"/home/green/CLOG/CLOG.asd" contains definition for system "clog". Please only define "CLOG" and secondary systems with a name starting with "CLOG/" (e.g. "CLOG/test") in that file.
WARNING: System definition file #P"/home/green/CLOG/CLOG.asd" contains definition for system "clog/tools". Please only define "CLOG" and secondary systems with a name starting with "CLOG/" (e.g. "CLOG/test") in that file.
While evaluating the form starting at line 11, column 0
  of #P"/home/green/CLOG/CLOG.asd":

debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD tid=11728 "main thread" RUNNING {1001120003}>: Error while trying to load definition for system CLOG from pathname /home/green/CLOG/CLOG.asd: Circular dependency: ((#<LOAD-OP > . #<SYSTEM "clog">) (#<LOAD-OP > . #<CL-SOURCE-FILE "clog" "CLOG">) (#<PREPARE-OP > . #<CL-SOURCE-FILE "clog" "CLOG">) (#<PREPARE-OP > . #<SYSTEM "clog">))

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry EVAL of current toplevel form.
  1: [CONTINUE                     ] Ignore error and continue loading file "/home/green/CLOG/CLOG.asd".
  2: [ABORT                        ] Abort loading file "/home/green/CLOG/CLOG.asd".
  3: [RETRY                        ] Retry #<DEFINE-OP > on #<UNDEFINED-SYSTEM "CLOG">.
  4: [ACCEPT                       ] Continue, treating #<DEFINE-OP > on #<UNDEFINED-SYSTEM "CLOG"> as having been successful.
  5:                                 Retry ASDF operation.
  6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
  7:                                 Retry ASDF operation.
  8:                                 Retry ASDF operation after resetting the configuration.
  9:                                 Exit debugger, returning to top level.

((LAMBDA (CONDITION) :IN PERFORM) #<CIRCULAR-DEPENDENCY {1005388273}>)
   error finding frame source: Bogus form-number: the source file has probably changed too much to cope with.
   source: NIL
```

**Comment by rabbibotton** [comment]
Did you do the steps on an empty directory? Also if the dir is called clog
likely to create issues also as system asd conflicts.

**Comment by atgreen** [comment]
It was the directory name.  Thanks!
