### ISSUE TITLE
OCICL latest redownloads packages

### ISSUE THREAD

**Issue by rabbibotton** [ocicl/ocicl#52]
It appears to me that ocicl latest is downloading the current versions again even if the same

**Comment by atgreen** [comment]
Checking the latest version tag in OCI registries is a slow operation.  You would need to do that to avoid downloading the latest if you already have it.   It is much slower than just downloading the latest code unconditionally.

I did, however, recently implement a change where `ocicl install foo` will only install `foo` if no version is already installed. `ocicl --force install foo` will force the download.   `ocicl install foo:VERSION` will also install VERSION of foo unconditionally.  So this is something.

```
green@fedora:~/git/ocicl/CCC$ time (oras repo tags ghcr.io/ocicl/cl-ppcre:latest && oras pull ghcr.io/ocicl/cl-ppcre:latest)
latest
20240503-80fb19d
Downloading f6b1b7496872 cl-ppcre-20240503-80fb19d.tar.gz
Downloaded  f6b1b7496872 cl-ppcre-20240503-80fb19d.tar.gz
Pulled [registry] ghcr.io/ocicl/cl-ppcre:latest
Digest: sha256:584907e0683621973579f397115945ef73e9d5b7afa77fae7cacecb3ad272f89

real	0m1.360s
user	0m0.103s
sys	0m0.045s
green@fedora:~/git/ocicl/CCC$ rm -rf *
green@fedora:~/git/ocicl/CCC$ time (oras pull ghcr.io/ocicl/cl-ppcre:latest)
Downloading f6b1b7496872 cl-ppcre-20240503-80fb19d.tar.gz
Downloaded  f6b1b7496872 cl-ppcre-20240503-80fb19d.tar.gz
Pulled [registry] ghcr.io/ocicl/cl-ppcre:latest
Digest: sha256:584907e0683621973579f397115945ef73e9d5b7afa77fae7cacecb3ad272f89

real	0m0.397s
user	0m0.060s
sys	0m0.028s
```
