### ISSUE TITLE
Proxy and repository location

### ISSUE THREAD

**Issue by MarcRohrer** [ocicl/ocicl#6]
Hi Anthony,

sorry, me again :-)

when I ran 

g:\lisp>ocicl install alexandria
Error: system alexandria not found.

http_proxy  and https_proxy were set to the proxy server but without user. I don't quite remember, but I think that was necessary for some other system. 
A message "login required" or something in that vain would be very helpful here.
With user/pwd added it worked fine, I would recommend adding the format somewhere in the readme, as this is a bit fiddly for a non experienced user.

How can I set the repository to be stored in some other directory than in the user profile?

Thanx!

Marc

**Comment by MarcRohrer** [comment]
I mean for the global...

**Comment by atgreen** [comment]
Right now it can only go in the user profile, but I could add an option to configure that at setup time.
As for the proxy settings, I can document something.  Did you just have to set https_proxy?  Or also http_proxy?
Thanks!

**Comment by MarcRohrer** [comment]
setup time would be perfect, I think.
I had set both previously, so I adapted both of them.
But I removed http_proxy and it still works, so http_proxy should suffice.

**Comment by atgreen** [comment]
Are you missing an "s" somewhere here? "But I removed http_proxy and it still works, so http_proxy should suffice."

I've added a GLOBALDIR optional argument to setup.  Please try it out.

Thanks!

**Comment by MarcRohrer** [comment]
Absolutely :-)

The correct sentence sould read:
But I removed http_proxy and it still works, so https_proxy should suffice.

Sorry for the Inconvenience!
