### ISSUE TITLE
OCICL should not hook into `asdf:load-asd`

### ISSUE THREAD

**Issue by mdbergmann** [ocicl/ocicl#62]
I'm using `asdf:load-asd` to load plugins into a project. When calling `load-asd` ocicl hooks into the call (by supplying searcher function to `asdf:*system-definition-search-functions*`) and tries to download the named system. However, the system should not be downloaded but indeed loaded from specified path to `load-asd`.

**Comment by mdbergmann** [comment]
If I understand it correctly then `load-asd` works so that `ASDF/SYSTEM-REGISTRY:SEARCH-FOR-SYSTEM-DEFINITION` should not find anything so that the previously registered (`'undefined-system`) with the path to the .asd (in asdf.lisp):

```
(let ((system (make-instance 'undefined-system
                                         :name primary-name :source-file pathname)))
              (register-system system)
```

and code that follows will load the system from the specified file.
But ocicl intercepts here and tries to load the system from it's sources instead which then prevents asdf to load the system from specified file.

Unfortunately I don't know the asdf sources well enough. Maybe my assumption of how `load-asd` works is wrong. But this is so, then I think ocicl should not intercept when `load-asd` was called.

**Comment by atgreen** [comment]
This is interesting.  I don't suppose you could change your code to do
something like...
```
(let ((ocicl-runtime:*download* nil))
    (load-my-plugin plugin-name))
```
?
(or, I suppose, do that conditionally if ocicl-runtime is loaded)

Also, if ocicl-runtime can't load it, I would expect asdf to keep trying
different methods.  Is that not what's happening?

**Comment by mdbergmann** [comment]
Setting `*download*` `NIL` works. I guess that could be a workaround for when `:OCICL` is found in `*features*`.
Generally though I think this changes behavior of `load-asd` which it should not.

**Comment by mdbergmann** [comment]
Hmm, well. This workaround then only works for `load-asd`. A succeeding `load-system` then again fails trying to download the system which is defined in the asd.
I'm not sure what's going on under the hoods there in asdf, I'll probably have to dig a bit into it.
In Quicklisp this procedure works OK. Wondering how this does it.

**Comment by mdbergmann** [comment]
Seems to work now. Not sure why or what has changed. Despite `load-asd` fails to download the system the rest of the process works now OK. Closing.
