### ISSUE TITLE
"ocicl install package-name" always downloads

### ISSUE THREAD

**Issue by jsparkes** [ocicl/ocicl#66]
This is a feature request.  "ocicl install XX" always downloads the XX package files, even if they already exist.  "ocicl install" only downloads packages that aren't locally available.   I'd like the first to act like the second.  You could even add a flag like "ocicl install --if-needed" to preserve the existing behaviour.

I'm trying to build lem on windows, and have .bat file with a bunch of "ocicl install" commands.  I'd like to be able to run it on each build.  I could just invoke "ocicl install" if the systems.csv exists, but that exceeds my meager ability to write windows bat scripts.

**Comment by atgreen** [comment]
Ok, try the latest version.  See what I changed in the README.  The --force option forces a download.
