### ISSUE TITLE
Tell user if ocicl can't find ocicl-oras

### ISSUE THREAD

**Issue by haze** [ocicl/ocicl#69]
I've installed `ocicl` from source by cloning this repository and running `sbcl —-load setup.lisp`. I've made sure `ocicl` is available in my `PATH`, and confirmed that `*features*` includes `:OCICL`, but I cannot resolve/download/use any packages.

When I try and `(asdf:load-system :str)`, I get this

```
debugger invoked on a ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread
#<THREAD tid=259 "main thread" RUNNING {7004AF0143}>:
  Component :STR not found
```

I'm also unable to view versions when using `ocicl list`:
![image](https://github.com/user-attachments/assets/8c4c8e0c-5f46-4f68-83b9-a4b4949b0cea)

**Comment by atgreen** [comment]
Are you logged into ghcr.io with an expired token or similar?  Just to be safe, run `ocicl-oras logout ghcr.io` and try again.  This happened to me last week.

**Comment by haze** [comment]
I wasn't aware that I needed to login in the first place

**Comment by atgreen** [comment]
You don't need to log in.  But if you were logged in with expired credentials then that would be a problem.

**Comment by atgreen** [comment]
If that still doesn't work, tell me what this says:
```
ocicl-oras pull ghcr.io/ocicl/str:latest
```

**Comment by haze** [comment]
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/5ad497a9-6d9d-4412-a07c-6d7a9b24dbf1">

**Comment by atgreen** [comment]
This is interesting.   Can you run "rm /Users/hbooth/.local/share/ocicl/asdf*", restart you sbcl and try again?

**Comment by haze** [comment]
There is a warning about the ASDF version not being sufficient. Would that do the trick?

![Uploading Screenshot 2024-08-24 at 8.18.32 PM.png…]()

**Comment by atgreen** [comment]
No, that's not it.  You can restore asdf.lisp by running 'ocicl setup' again.   What does "ocicl -v install str" say?

**Comment by haze** [comment]
I lost the terminal session, but it exited with a return value of `127`. I then figured that I also needed `ocicl-oras` on my `PATH` as well, that's my fault. After I made that available, all avenues of installing packages (through ASDF and `ocicl install` worked.)

**Comment by atgreen** [comment]
Thanks for figuring this out!  ocicl should really tell the user if it can't find ocicl-oras.  I'm reopening this until it is fixed.
