### ISSUE TITLE
ocicl list

### ISSUE THREAD

**Issue by MarcRohrer** [ocicl/ocicl#7]
I was quite confused about:

```
H:\src\lisptest>ocicl list

H:\src\lisptest>
```

whereas

```
H:\src\hl7>npm list
hl7@1.0.0 H:\src\hl7
+-- dotenv@16.0.3
+-- node-windows@1.0.0-beta.8
`-- postgres@3.3.4
H:\src\hl7>
```

Or ist there another means to quickly list the installed packages?

**Comment by atgreen** [comment]
"ocicl list" lists the versions of systems available in the OCI registry.

$ ocicl list cl-ppcre
cl-ppcre:
 latest
 20230611-93bd7cf
 20230511-b4056c5a
 20230510-b4056c5a

 To see what you have local, just look in your systems dir.

**Comment by MarcRohrer** [comment]
I guess one can also look in systems.csv.
Both is not comfortable.
I recommend the same as npm.
