### ISSUE TITLE
Possibly use the sharplispers' repos for projects that no longer have the original maintainer

### ISSUE THREAD

**Issue by ellisvelo** [ocicl/ocicl#71]
Hello,

Thanks for creating ocicl! It has been working out great and I like how it's possible to use a particular version. One of the things that I came across is that some of the cl systems are not being maintained and the sharplispers have taken on maintenance for the community. Can ocicl make use of the sharplispers repos?

For example, I'm using `cl-json`, but it has some warnings because the original maintainer has stopped taking care of it. There is a later version [sharperlispers/cl-json](https://github.com/sharplispers/cl-json) that does address the warnings though.

**Comment by atgreen** [comment]
Thank you!  And, yes, of course. I've just updated cl-json.  Just file issues here or, ideally, at github.com/ocicl/request-system-additions-here.
