### ISSUE TITLE
ocicl not updating for CLOG

### ISSUE THREAD

**Issue by dbotton-work** [ocicl/ocicl#72]
OCICL stopped updating for CLOG. Why did this happen and what can be done in the future when this does happen?

**Comment by atgreen** [comment]
It looks like git has not been very reliable within github actions recently.  I'll see about making the action more robust.
![image](https://github.com/user-attachments/assets/c56259b8-2854-40d9-96af-625d31429484)

**Comment by dbotton-work** [comment]
Awesome, I am really loving ocicl in my non hobby projects, it is the best
solution for serious maintenance of third party libraries.

Thanks!

**Comment by atgreen** [comment]
Let's see if this fixes things: https://github.com/ocicl/ocicl-sandbox/commit/1905f06ce275ef041f15b82eb59e4adde561d30d

I'm going to close this for now.  Thanks!
