### ISSUE TITLE
Revisiting ocicl "projects"

### ISSUE THREAD

**Issue by dieggsy** [ocicl/ocicl#78]
This sounds similar to #45, but I think I'm asking about something different. Right now, the ocicl automatic download on `require` will install systems to the current directory.  This means if I'm in some sub-directory of my project, ocicl won't know that I might already have a `systems` directory at some higher level, and just create a new `systems` and `systems.csv` at the current subdirectory.

It would be nice if ocicl could "know" that I'm in an ocicl project and use that to install deps - e.g. if it searched for an `.ocicl` directory somewhere up the path and instal there. Otherwise, I'd want it to install globally.

My reasoning is I'd like to be able to `require` a new dependency from any dir in my project. If I am not in a project, I likely do not want to just install systems wherever I happen to be (and would prefer a global install in that case). Of course, all of this is avoided by simply starting lisp in "the right place", but I have to remember to do that. 

I'm not sure if this is universally desirable - probably not given the current design. Perhaps this feature could be requested as part of the setup.

**Comment by mdbergmann** [comment]
This is what I also think would be great, if ocicl could be 'aware' of being in a project where dependencies have already been pulled by ocicl.

I'm not sure though that "otherwise" it should be global.

**Comment by rudolfochrist** [comment]
This would be great. I imaging traversing up until we find a `systems.csv` and install dependencies there. 
In my opinion, dependencies should only be installed globally when the `--global` flag is passed. If `ocicl` can't find a `systems.csv` in any parent directory then it should created a new one in the current directory and use that to install dependencies.

**Comment by dieggsy** [comment]
Eh, I'll agree with @mdbergmann's doubt and think that @rudolfochrist's proposed default is probably saner than mine. My only issue with specifically looking for `systems.csv` is it's not a name that's particularly unique to ocicl, but it is the current one anyway so maybe that would be fine. There is another ticket addressing renaming "systems", too.

**Comment by atgreen** [comment]
> This would be great. I imaging traversing up until we find a `systems.csv` and install dependencies there. In my opinion, dependencies should only be installed globally when the `--global` flag is passed. If `ocicl` can't find a `systems.csv` in any parent directory then it should created a new one in the current directory and use that to install dependencies.

I like this idea.

**Comment by atgreen** [comment]
That was a great idea. Thanks!  I really like how it works now.

**Comment by dieggsy** [comment]
This is awesome, thanks!
