### ISSUE TITLE
How to publish software?

### ISSUE THREAD

**Issue by shamazmazum** [ocicl/ocicl#83]
Hi! I would like to start using ocicl, but I cannot install a dependency:

~~~~
Error: system stateless-iterators not found.
~~~~

How to publish it? The documentation mentions a github action, namely `ocicl-action`, but there is no information how it can be used. Is it possible to publish anything? Please, improve the documentation!

**Comment by rudolfochrist** [comment]
See this section of the [README](https://github.com/ocicl/ocicl/blob/main/README.md#systems)

> Systems
> -------
> 
> Systems managed by ``ocicl`` are maintained in github, at
> [https://github.com/ocicl](https://github.com/ocicl).  Each system has
> its own source repo, with a ``README.org`` file containing everything
> required to build and publish to the OCI registry via github actions.
> 
> The list of ocicl systems is always available at
> [https://raw.githubusercontent.com/ocicl/request-system-additions-here/main/all-ocicl-systems.txt](https://raw.githubusercontent.com/ocicl/request-system-additions-here/main/all-ocicl-systems.txt).
> 
> Contributions are welcome and appreciated!  See
> https://github.com/ocicl/request-system-additions-here for details.

Since `stateless-iterators` is currently not found in the ocicl repo, you have to request its addition here: https://github.com/ocicl/request-system-additions-here

**Comment by shamazmazum** [comment]
Oh, I missed it somehow. Thanks!

**Comment by atgreen** [comment]
I've just added it.  Thanks!
